name = "pai-fat-loss"
compatibility_date = "2026-08-21"
pages_build_output_dir = "dist"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"
